<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>链式调用</title>
</head>
<body>

<script>



  // 网络请求：aaa ->自己处理（10行）
  // 处理： aaa111 -> 自己处理（10行）
  // 处理： aaa222 ->自己处理
/* new Promise((resolve, reject)=>{
    setTimeout(()=>{
      resolve("aaa");
    },1000)
  }).then(res=>{
    //1.自己处理十行
    console.log(res,"第一层的10行处理代码");

    //2. 对结果进行第一部的处理
    return new Promise((resolve,reject)=>{
      //resolve(res+"111");
      reject('err!');
    })

  }).then(res=>{
    console.log(res,"第二层的10行处理代码");

    return new Promise((resolve)=>{
      resolve(res+"222")
    })
  }).then(res=>{
    console.log(res,"第三层的10行处理代码");
  }).catch(err=>{
   console.log(err)
 })*/

  // new Promise（resolve=》resolve（结果））简写
/*  new Promise((resolve, reject)=>{
    setTimeout(()=>{
      resolve("aaa");
    },1000)
  }).then(res=>{
    //1.自己处理十行
    console.log(res,"第一层的10行处理代码");

    //2. 对结果进行第一步的处理
    return Promise.resolve(res+"111")

  }).then(res=>{
    console.log(res,"第二层的10行处理代码");

    return Promise.resolve(res+"222")
  }).then(res=>{
    console.log(res,"第三层的10行处理代码");
  })*/

  //对以上的简写的简写 省略掉Promise.resolve
  new Promise((resolve, reject)=>{
    setTimeout(()=>{
      resolve("aaa");
    },1000)
  }).then(res=>{
    //1.自己处理十行
    console.log(res,"第一层的10行处理代码");

    //2. 对结果进行第一步的处理
    //return Promise.reject('err message!!!');
    //手动抛出自定义异常
    throw "error myError "

  }).then(res=>{
    console.log(res,"第二层的10行处理代码");

    return (res+"222")
  }).then(res=>{
    console.log(res,"第三层的10行处理代码");
  }).catch(err=>{
    console.log(err);
  })


</script>

</body>
</html>